### ISSUE TITLE
Add support for adding features

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/luatex-harfbuzz#3]

**Comment by khaledhosny** [comment]
I suggest using node attributes to pass the features to avoid breaking the runs, then collect them during shaping and pass them as HarfBuzz features array. So that it is possible to, say, turn on `cvXX` feature for a character in the middle of an Arabic word without breaking the shaping and other features.

**Comment by deepakjois** [comment]
Closed in favor of deepakjois/ufylayout#3
